apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-config
data:
  logfile: logs/server
  google_drive_model_pickle: https://drive.google.com/uc?export=download&id=1RQ2wVglhUZo6Ww8bmurmoXzzop14obmU
  google_drive_input_schema: https://drive.google.com/uc?export=download&id=1NFgA5jjh6SIRF6qbRU8UfTaBtFnr4xjk
  google_drive_input_stats: https://drive.google.com/uc?export=download&id=1XohGwqfpCVDULdUnlegfe_h0JymhWPeT
  log_to_file: "False"
  log_stdout: "True"
  logging_level: info
