defaults:
  - _self_
  - estimator: log-reg
  - override hydra/job_logging: dot-formatted

dir_prefix: ../../..
metrics_path: ${dir_prefix}/metrics/

dataset:
  download: True
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data
  dataset_dir: ${dir_prefix}/data/raw
  dataset_filename: breast-cancer-dataset.csv
  random_state: 100

splitter:
  validation: 0.2
  random_state: ${dataset.random_state}

feature:
  target: diag
  numeric_imputer_strategy: mean
  random_state: ${dataset.random_state}
  scaler_type: standard
  encoder_type: ohe
