model_artifact_path: "artifacts/"
metrics_path: "metrics/"

data_params:
  source_url: "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
  dataset_dir: "data/raw"
  dataset_filename: "breast-cancer-dataset.csv"
  random_state: 100

split_params:
  validation: 0.2
  random_state: $"data_params.random_state"

feature_params:
  target: "diag"
  random_state: $"data_params.random_state"

training_params:
  model_type: "LogisticRegression"
  model_params:
    max_iters: 1500
    penalty: "elasticnet"
    l1_ratio: 0.8
    random_state: $"data_params.random_state"
    solver: "saga"
