defaults:
  - _self_
  - override hydra/job_logging: dot-formatted

artifact: ???
input: ???
output: prediction.json
dir_prefix: ../../..

inference:
  artifact: ${dir_prefix}/${artifact}
  input_features: ${dir_prefix}/${input}
  output_target:  ${output}
