_target_: settings.root_params.RootConfig

defaults:
  - _self_
  - estimator: log-reg
  - feature: no-pca
  - override hydra/job_logging: dot-formatted

dir_prefix: ../../..
random_state: 100

dataset:
  _target_: settings.data_params.DatasetConfig
  download: True
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data
  dataset_dir: ${dir_prefix}/data/raw
  dataset_filename: breast-cancer-dataset.csv
  random_state: ${random_state}

splitter:
  _target_: settings.data_params.SplitConfig
  validation: 0.2
  random_state: ${random_state}
