name: Training Pipeline

on:
  push:
    branches: [ homework1 ]

  workflow_dispatch:

jobs:
  # this workflow contains
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Checkout to project dir
        run: |
          cd ml_project

      - name: Lint with Flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest and save the log
        run: |
          python -m pytest -v | tee pytest-results.log
      
      - name: Run the training pipeline
        run: |
          python pipeline.py | tee pipeline.log

      - name: Save the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            *.log
            artifacts/*.pkl
        if: ${{ always() }}
