name: Training Pipeline

on:
  push:
    branches: [ workflow-hotfix ]

  workflow_dispatch:

jobs:
  # this workflow contains
  # python setup, dependency installation,
  # linting and unit-testing with pytest
  # as a last step, training pipeline is run
  # and the artifacts are also saved
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_project

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest and save the log
        run: |
          python -m pytest -v | tee pytest-results.log

      - name: Run the training pipeline
        run: |
          python pipeline.py hydra/job_logging=console-dot-formatted | tee pipeline.log

      - name: Save the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./*.log
            artifacts/*.pkl
        if: ${{ always() }}
